# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_sc_atac_trim_barcode <- function(outfq, r1, r3, barcode_file, start, len, umi_start, umi_len, umi_in, write_gz) {
    invisible(.Call(`_seqATAC_rcpp_sc_atac_trim_barcode`, outfq, r1, r3, barcode_file, start, len, umi_start, umi_len, umi_in, write_gz))
}

rcpp_sc_atac_trim_barcode_paired <- function(outfq, r1, r2_list, r3, write_gz) {
    invisible(.Call(`_seqATAC_rcpp_sc_atac_trim_barcode_paired`, outfq, r1, r2_list, r3, write_gz))
}

rcpp_sc_atac_bam_tagging <- function(inbam, outbam, bc, mb, nthreads) {
    invisible(.Call(`_seqATAC_rcpp_sc_atac_bam_tagging`, inbam, outbam, bc, mb, nthreads))
}

